export const UserCss = [':host table{border-collapse:collapse; text-align: center; margin:50px auto;}',
':host th,td{border: 1px solid #FFBFBF; padding: 5px;}',
':host th{background: #FF9673; color: #ffffff; padding: 10px;}',
':host input[checked]{text-align: center;}',
':host td>input{border: none; box-shadow:2px 2px 1px #bdbdae;}',
':host td>input[type="text"]{background-color: #ffdfbf; padding: 5px;}',
':host td>input:focus{background-color: #ffffbf;}',
':host td>input[type="checkbox"]{box-shadow: none;}',
':host /deep/ input{border: none; box-shadow:2px 2px 1px #bdbdae;}',
':host /deep/ input[type="text"]{background-color: #ffdfbf; padding: 5px;}',
':host /deep/ input:focus{background-color: #ffffbf;}',
':host /deep/ input[type="checkbox"]{box-shadow: none;}'];